### ISSUE TITLE
More control over RSS feeds

### ISSUE THREAD

**Issue by h3xium** [adamsanderson/brook#18]
Hi, I hope you are ok with some more contributions. I'd like to get involved with some open-source projects and I enjoy using your Firefox Addon.

I'd like to add the RSS feed for https://docs.vmware.com/en/VMware-vSphere/ but Brook is unable to pick it up. I know the page has an RSS feed and would like to add some additional functionality to manually add the feed URL rather than having to rely on the extension to pick up that there is a feed.

Cheers
Dean

**Comment by smonff** [comment]
Same here with [mediapart.fr](https://www.mediapart.fr) that have a [valid feed](https://www.mediapart.fr/articles/feed) that is not detected. 

It would be nice to be able to have a *Manually add feed* feature.

**Comment by adamsanderson** [comment]
Oh my goodness! Two real people who used this once, first of all thank you @h3xium and @smonff.
I have no idea how I missed this ages ago, but if you haven't deleted Brook in a blaze of sadness, you actually can manually add RSS feeds.

There's a debug menu triggered by shift clicking on the menu in the top right corner. Please don't click `Reset Data` it will do exactly what it says, and I don't believe it prompts you because I only use it for testing :) 

That said, I'll take a look at the links y'all posted and see if there's anything I can do to pick these links up.

Thank you infinitely!
  .adam

**Comment by adamsanderson** [comment]
For the first site, you can now detect feeds if you visit them directly (https://github.com/adamsanderson/brook/commit/a1ec80f02a037da3183a79e406720510f7219e7d).  For mediapart.fr, clicking the feed link triggers a download which I don't think I can intercept without requesting more permissions than I'd like to.  I'll look for better ways to detect it.

I'll wrap this up into a new version in the next few days.

**Comment by adamsanderson** [comment]
Well, life intervenes, but the newest package has been published and should be available shortly.
